#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres <<-EOSQL
    CREATE DATABASE IF NOT EXISTS "$IDENTITY_DB";
    CREATE DATABASE IF NOT EXISTS "$EMPLOYEE_DB";
    CREATE DATABASE IF NOT EXISTS "$CONTRACTOR_DB";
    CREATE DATABASE IF NOT EXISTS "$CUSTOMER_DB";
    CREATE DATABASE IF NOT EXISTS "$SUPPLIER_DB";
    CREATE DATABASE IF NOT EXISTS "$METER_READING_DB";
EOSQL
