#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres <<-EOSQL
    CREATE DATABASE "$IDENTITY_DB";
    CREATE DATABASE "$EMPLOYEE_DB";
    CREATE DATABASE "$CONTRACTOR_DB";
    CREATE DATABASE "$CUSTOMER_DB";
    CREATE DATABASE "$SUPPLIER_DB";
    CREATE DATABASE "$METER_READING_DB";
EOSQL
